# Generated by Django 2.1.4 on 2019-04-26 05:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190424_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bcont',
            field=jsonfield.fields.JSONField(blank=True, default={'blacklist': []}),
        ),
    ]
