# Generated by Django 2.1.4 on 2019-04-27 06:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_bcont'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='elist',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='profile',
            name='econt',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bcont',
            field=jsonfield.fields.JSONField(blank=True, default={'blacklist': [], 'blocked': []}),
        ),
    ]
